# Generated by Django 2.1 on 2019-03-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
    ]
