# Generated by Django 2.1 on 2019-03-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190306_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stack',
            field=models.CharField(max_length=255),
        ),
    ]
