# Generated by Django 2.1 on 2019-03-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190306_1058'),
    ]

    operations = [
    ]
